overwriteIndices: False
downloadTarballs: True
downloadFreemium: False
parseFreemium: True
downloadsDirPath: '/root/data/JO/'
dataDirPath: '/root/data/JO/'
dataRegex: '**/*.tar.gz'
logsDirPath: '/root/logs/JO/'
