overwriteIndices: False
downloadTarballs: True
downloadFreemium: False
parseFreemium: True
downloadsDirPath: '/root/data/JO/'
dataDirPathRegex: '/root/data/JO/**/*.tar.gz'
logsDirPath: '/root/logs/JO/'
