overwriteIndices: False
downloadTarballs: True
downloadFreemium: False
parseFreemium: True
downloadDirPath: '/root/data/JO/'
dataDirPathRegex: '/root/data/JO/**/*.tar.gz'
logDirPath: '/root/logs/JO/'
