overwriteIndices: False
downloadTarballs: True
downloadFreemium: False
parseFreemium: True
downloadsDirPath: '/home/alexis/bureau_ouvert/jo/data/JORFSIMPLE/'
logsDirPath: '/home/alexis/bureau_ouvert/jo/logs/JORFSIMPLE/'
dataRegex: '**/*.tar.gz'
xmlStructuresDirPath: '/home/alexis/bureau_ouvert/jo/xmlStructures/'
